### ISSUE TITLE
Improve EmailAddress messages, many missing input argument.

### ISSUE THREAD

**Issue by mP1** [mP1/walkingkooka#1145]
> java.lang.IllegalArgumentException: Email too long
> 	at walkingkooka.net.email.EmailAddressParserWith.fail(EmailAddressParserWith.java:67)
> 	at walkingkooka.net.email.EmailAddressParserWith.emailTooLong(EmailAddressParserWith.java:38)
> 	at walkingkooka.net.email.EmailAddressParser.parse(EmailAddressParser.java:46)
> 	at walkingkooka.net.email.EmailAddressParserWith.parseOrFail(EmailAddressParserWith.java:29)
> 	at walkingkooka.net.email.EmailAddress.parse(EmailAddress.java:56)
> 	at walkingkooka.net.email.EmailAddressTest.lambda$withFails$1(EmailAddressTest.java:196)
> 

> java.lang.IllegalArgumentException: Host contains invalid character ']' at 12
> 	at walkingkooka.net.HostAddress.fail(HostAddress.java:164)
> 	at walkingkooka.net.HostAddress.with(HostAddress.java:137)
> 	at walkingkooka.net.HostAddress.withEmail(H

**Comment by mP1** [comment]
Finished by #1148
